# -*- coding: utf-8 -*-
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

'''
Contains basic model properties and their definitions.

This module contains all the basic properties used in an NWN model.

@author: Erik Ylipää
'''
    
def get_animation_categories():
    """ Build and return the animation data """
    return classifications

walkmesh_materials =     [{"name": "Dirt", "color": (0.3,0.3,0.2)},
                           {"name": "Obscuring", "color": (1,1,1)},
                           {"name": "Grass", "color": (0, 0.5, 0)},
                           {"name": "Stone", "color": (0.2, 0.2, 0.2)},
                           {"name": "Wood", "color": (0.04,0.01, 0.01)},
                           {"name": "Water", "color": (0, 0, 0.7)}, 
                           {"name": "Nonwalk", "color": (0.7, 0, 1)},
                           {"name": "Transparent", "color": (0, 1, 1)},
                           {"name": "Carpet", "color": (0.2, 0.05, 0.1)},
                           {"name": "Metal", "color": (0.02,0.02,0.02)},
                           {"name": "Puddles", "color": (0, 0.5, 0.5)}, 
                           {"name": "Swamp", "color": (0, 0.25, 0)},
                           {"name": "Mud", "color": (0.36, 0.2, 0.1)},
                           {"name": "Leaves", "color": (0, 0.75, 0)},
                           {"name": "Lava", "color": (0.75, 0, 0)},
                           {"name": "BottomlessPit", "color": (0.015, 0.005, 0.03)}, 
                           {"name": "DeepWater", "color": (0, 0.005, 0.08)},
                           {"name": "Door", "color": (0.14, 0.05, 0.02)}, 
                           {"name": "Snow", "color": (0.5,0.5,1)}, 
                           {"name": "Sand", "color": (0.4, 0.3, 0.1)}
                 ]

classifications = ["Character", "Item", "Door", "Effect", "GUI", "Tile"]
animation_names_dict = {"Character": {"Player": [], 
                                 "Full": [], 
                                 "Simple" : [], 
                                 "Large": []},
                   "Item": {"Item": []},
                   "Tile": {"Tile": []},
                   "Effect": {"Effect": []}
                   }

animation_names = {
'default': ["Character"],
'---ITEM---': ["Character"],
'off': ["Character"],
'off2on': ["Character"],
'on': ["Character"],
'on2off': ["Character"],
'--------': ["Character"],
'close': ["Character"],
'close2open': ["Character"],
'open': ["Character"],
'open2close': ["Character"],
'damage': ["Character"],
'die': ["Character"],
'dead': ["Character"],
'--------': ["Character"],
'-CREATURE': ["Character"],
'--movement--': ["Character"],
'cpause1': ["Character"],
'creadyr': ["Character"],
'creadyl': ["Character"],
'cwalk': ["Character"],
'crun': ["Character"],
'ccwalkf': ["Character"],
'ccwalkb': ["Character"],
'ccwalkl': ["Character"],
'ccwalkr': ["Character"],
'cgetmid': ["Character"],
'cgetmidlp': ["Character"],
'ccturnr': ["Character"],
'ccturnl': ["Character"],
'--attack--': ["Character"],
'ca1slashl': ["Character"],
'ca1slashr': ["Character"],
'ca1stab': ["Character"],
'cclosel': ["Character"],
'ccloseh': ["Character"],
'creach': ["Character"],
'--defend--': ["Character"],
'cdamagel': ["Character"],
'cdamager': ["Character"],
'cdamages': ["Character"],
'cparryr': ["Character"],
'cparryl': ["Character"],
'cdodgelr': ["Character"],
'cdodges': ["Character"],
'--down--': ["Character"],
'cguptokdb': ["Character"],
'cgustandb': ["Character"],
'ckdbck': ["Character"],
'ckdbckps': ["Character"],
'ckdbckdmg': ["Character"],
'ckdbckdie': ["Character"],
'cdead': ["Character"],
'--other--': ["Character"],
'ctaunt': ["Character"],
'cconjure1': ["Character"],
'ccastoutlp': ["Character"],
'ccastout': ["Character"],
'cspasm': ["Character"],
'cappear': ["Character"],
'cdisappear': ["Character"],
'cdisappearlp': ["Character"],
'chturnl': ["Character"],
'chturnr': ["Character"],
'--------': ["Character"],
'-ENDcreature': ["Character"],
'--------': ["Character"],
'1hslashl': ["Character"],
'1hslashr': ["Character"],
'1hslasho': ["Character"],
'1hstab': ["Character"],
'1hcloseh': ["Character"],
'1hclosel': ["Character"],
'1hreach': ["Character"],
'2hslashl': ["Character"],
'2hslashr': ["Character"],
'2hslasho': ["Character"],
'2hstab': ["Character"],
'2hcloseh': ["Character"],
'2hclosel': ["Character"],
'2hreach': ["Character"],
'plslashl': ["Character"],
'plslashr': ["Character"],
'plslasho': ["Character"],
'plstab': ["Character"],
'plcloseh': ["Character"],
'plclosel': ["Character"],
'plreach': ["Character"],
'2wslashl': ["Character"],
'2wslashr': ["Character"],
'2wslasho': ["Character"],
'2wstab': ["Character"],
'2wcloseh': ["Character"],
'2wclosel': ["Character"],
'2wreach': ["Character"],
'bowshot': ["Character"],
'bowshoto': ["Character"],
'xbowshot': ["Character"],
'xbowshoto': ["Character"],
'nwslashl': ["Character"],
'nwslashr': ["Character"],
'nwslasho': ["Character"],
'nwstab': ["Character"],
'nwkickl': ["Character"],
'nwkickr': ["Character"],
'nwkicks': ["Character"],
'nwcloseh': ["Character"],
'nwclosel': ["Character"],
'nwreach': ["Character"],
'throwr': ["Character"],
'conjure1': ["Character"],
'conjure2': ["Character"],
'castout': ["Character"],
'castoutlp': ["Character"],
'castself': ["Character"],
'castselflp': ["Character"],
'castup': ["Character"],
'castuplp': ["Character"],
'castarea': ["Character"],
'castarealp': ["Character"],
'castpoint': ["Character"],
'castpointlp': ["Character"],
'appear': ["Character"],
'disappear': ["Character"],
'disappearlp': ["Character"],
'1hparryl': ["Character"],
'1hparryr': ["Character"],
'1hparrys': ["Character"],
'2hparryl': ["Character"],
'2hparryr': ["Character"],
'2hparrys': ["Character"],
'plparryl': ["Character"],
'plparryr': ["Character"],
'plparrys': ["Character"],
'2wparryl': ["Character"],
'2wparryr': ["Character"],
'2wparrys': ["Character"],
'shieldl': ["Character"],
'shieldr': ["Character"],
'shields': ["Character"],
'dodgelr': ["Character"],
'dodges': ["Character"],
'1hreadyr': ["Character"],
'1hreadyl': ["Character"],
'2hreadyr': ["Character"],
'2hreadyl': ["Character"],
'plreadyr': ["Character"],
'plreadyl': ["Character"],
'2wreadyr': ["Character"],
'2wreadyl': ["Character"],
'bowrdy': ["Character"],
'xbowrdy': ["Character"],
'xbowr': ["Character"],
'nwreadyl': ["Character"],
'nwreadyr': ["Character"],
'damagel': ["Character"],
'damager': ["Character"],
'damages': ["Character"],
'damageb': ["Character"],
'kdfnt': ["Character"],
'kdfntps': ["Character"],
'kdfntdmg': ["Character"],
'kdfntdie': ["Character"],
'deadfnt': ["Character"],
'gutokdf': ["Character"],
'gustandf': ["Character"],
'kdbck': ["Character"],
'kdbckps': ["Character"],
'kdbckdmg': ["Character"],
'kdbckdie': ["Character"],
'deadbck': ["Character"],
'gutokdb': ["Character"],
'gustandb': ["Character"],
'spasm': ["Character"],
'walk': ["Character"],
'walkdead': ["Character"],
'walkinj': ["Character"],
'walk_swordr': ["Character"],
'walk_swordl': ["Character"],
'walk_shieldl': ["Character"],
'walk_bowl': ["Character"],
'pauseturn': ["Character"],
'pausewalkl': ["Character"],
'pausewalkr': ["Character"],
'pausewalkfl': ["Character"],
'pausewalkfr': ["Character"],
'run': ["Character"],
'runfl': ["Character"],
'runfr': ["Character"],
'run_bowl': ["Character"],
'run_swordl': ["Character"],
'run_swordr': ["Character"],
'run_shieldl': ["Character"],
'cwalkf': ["Character"],
'cwalkb': ["Character"],
'cwalkl': ["Character"],
'cwalkr': ["Character"],
'cturnr': ["Character"],
'pause1': ["Character"],
'pause2': ["Character"],
'hturnl': ["Character"],
'hturnr': ["Character"],
'plpause1': ["Character"],
'2hpause1': ["Character"],
'pausesh': ["Character"],
'pausebrd': ["Character"],
'pausetrd': ["Character"],
'pausepsn': ["Character"],
'listen': ["Character"],
'kneel': ["Character"],
'meditate': ["Character"],
'worship': ["Character"],
'salute': ["Character"],
'lookfar': ["Character"],
'bow': ["Character"],
'sitdown': ["Character"],
'sit': ["Character"],
'standup': ["Character"],
'sitcross': ["Character"],
'sitcrossps': ["Character"],
'drink': ["Character"],
'read': ["Character"],
'torchr': ["Character"],
'torchl': ["Character"],
'steal': ["Character"],
'tlknorm': ["Character"],
'tlkplead': ["Character"],
'tlkforce': ["Character"],
'tlklaugh': ["Character"],
'greeting': ["Character"],
'taunt': ["Character"],
'getlow': ["Character"],
'getlowlp': ["Character"],
'getlowend': ["Character"],
'getmid': ["Character"],
'getmidlp': ["Character"],
'getmidend': ["Character"],
'victoryfr': ["Character"],
'victorymg': ["Character"],
'victoryth': ["Character"],
'drwleft': ["Character"],
'drwright': ["Character"],
'---------': ["Character"],
'ca1slashl': ["Character"],
'ca1slashr': ["Character"],
'ca1stab': ["Character"],
'ccloseh': ["Character"],
'cclosel': ["Character"],
'creach': ["Character"],
'cparryl': ["Character"],
'cparryr': ["Character"],
'cparrys': ["Character"],
'cdodgelr': ["Character"],
'cdodges': ["Character"],
'creadyr': ["Character"],
'creadyl': ["Character"],
'cdamagel': ["Character"],
'cdamager': ["Character"],
'cdamages': ["Character"],
'ckdbck': ["Character"],
'ckdbckps': ["Character"],
'ckdbckdmg': ["Character"],
'ckdbckdie': ["Character"],
'cguptokdb': ["Character"],
'cgustandb': ["Character"],
'cdead': ["Character"],
'cwalk': ["Character"],
'crun': ["Character"],
'ccwalkf': ["Character"],
'ccwalkb': ["Character"],
'ccwalkl': ["Character"],
'ccwalkr': ["Character"],
'ccturnr': ["Character"],
'cpause1': ["Character"],
'chturnl': ["Character"],
'chturnr': ["Character"],
'cgetmid': ["Character"],
'cgetmidlp': ["Character"],
'cgetmidend': ["Character"],
'ctaunt': ["Character"],
'cconjure1': ["Character"],
'ccastout': ["Character"],
'ccastoutlp': ["Character"],
'cappear': ["Character"],
'cdisappear': ["Character"],
'cdisappearlp': ["Character"],
'---------': ["Character"],
'ca2slashl': ["Character"],
'ca2slashr': ["Character"],
'ca2stab': ["Character"],
'ccastself': ["Character"],
'creadyrtw': ["Character"],
'creadyltw': ["Character"],
'ckdfnt': ["Character"],
'ckdfntps': ["Character"],
'ckdfntdie': ["Character"],
'cgutokdf': ["Character"],
'cgustandf': ["Character"],
'cspasm': ["Character"],
'cwalkinj': ["Character"],
'cpause2': ["Character"],
'ctalk': ["Character"],
'cvictory': ["Character"],
'---------': ["Character"],
'custom1start': ["Character"],
'custom1lp': ["Character"],
'custom1end': ["Character"],
'custom2start': ["Character"],
'custom2lp': ["Character"],
'custom2end': ["Character"],
'custom3start': ["Character"],
'custom3lp': ["Character"],
'custom3end': ["Character"],
'custom4start': ["Character"],
'custom4lp': ["Character"],
'custom4end': ["Character"],
'custom5start': ["Character"],
'custom5lp': ["Character"],
'custom5end': ["Character"],
'custom6start': ["Character"],
'custom6lp': ["Character"],
'custom6end': ["Character"],
'custom7start': ["Character"],
'custom7lp': ["Character"],
'custom7end': ["Character"],
'custom8start': ["Character"],
'custom8lp': ["Character"],
'custom8end': ["Character"],
'custom9start': ["Character"],
'custom9lp': ["Character"],
'custom9end': ["Character"],
'custom10start': ["Character"],
'custom10lp': ["Character"],
'custom10end': ["Character"],
'': ["Character"],
'on': ["Character"],
'off': ["Character"],
'default': ["Character"],
'tiledefault': ["Character"],
'animloop01': ["Character"],
'animloop02': ["Character"],
'animloop03': ["Character"],
'Day': ["Character"],
'Day2Night': ["Character"],
'Night': ["Character"],
'Night2Day': ["Character"],
'default': ["Character"],
'tiledefault': ["Character"],
'animloop01': ["Character"],
'animloop02': ["Character"],
'animloop03': ["Character"],
'Day': ["Character"],
'Day2Night': ["Character"],
'Night': ["Character"],
'Night2Day': ["Character"],
}